### ISSUE TITLE
LICENSE file

### ISSUE THREAD

**Issue by Bosch-Eli-Black** [JetBrains/svg-mixer#35]
Hello,

Could you please add a LICENSE file to the project?

**Comment by kisenka** [comment]
Hi! I've added info about license to [README](https://github.com/kisenka/svg-mixer#license)

**Comment by Bosch-Eli-Black** [comment]
Thanks, man :)

**Comment by polkovnikov-ph** [comment]
Could you please reopen this? We have `svg-baker-runtime` (with MIT license in its `package.json`), but there is no `LICENSE` file attached to it.

**Comment by Bosch-Eli-Black** [comment]
I'm thankful that @kisenka added licensing information, but admittedly, having a LICENSE file with the full text of the Apache 2 license in it would be better for us, too :)

I think this also may be required for the code to be truly licensed under Apache 2.

**Comment by kisenka** [comment]
Why license file is required? Are you sure? Could you provide a proof link?

**Comment by polkovnikov-ph** [comment]
@kisenka Merely mentioning license name is not enough. `MIT license` is a scheme of license. It tells about the terms, but doesn't mention what is the party that enforces it. License file has author's name mentioned.

While with `MIT` problem the issue is mostly formal (but, please, provide that file anyway), `Apache 2.0` without a license file makes the library unusable. Apache license requires users of the library to provide text of the license with binary distribution, while it doesn't exist at all.

**Comment by Bosch-Eli-Black** [comment]
This also helps out tools such as [license-checker](https://www.npmjs.com/package/license-checker) that extract licenses from packages.

**Comment by Bosch-Eli-Black** [comment]
`babel` also recently went through a similar issue, and added LICENSE files to their projects: https://github.com/babel/babel/pull/7308#issuecomment-367615152

**Comment by kisenka** [comment]
@Bosch-Eli-Black @polkovnikov-ph okay, I'll do it ASAP

**Comment by Bosch-Eli-Black** [comment]
@kisenka Yay! Thank you, man :)

**Comment by polkovnikov-ph** [comment]
@kisenka Great! Thanks!

**Comment by kisenka** [comment]
Sorry for delay gyus, I've published patch versions of all packages with LICESE file, please check.

**Comment by polkovnikov-ph** [comment]
@kisenka 

https://github.com/JetBrains/svg-mixer/tree/master/packages/svg-mixer#license

The link doesn't lead anywhere :)

**Comment by kisenka** [comment]
@polkovnikov-ph fixed now

**Comment by Bosch-Eli-Black** [comment]
Thanks, man :)
