### ISSUE TITLE
sprite.svg doesn't seem to be generated when using postcss-cli

### ISSUE THREAD

**Issue by thollander** [JetBrains/svg-mixer#75]
When using `postcss-cli` without any bundler, the `sprite.svg` is not generated (whereas the CSS file is changed). 

Repo to reproduce : [postcss-svg-mixer-test](https://github.com/thollander/postcss-svg-mixer-test)

Is it due to the webpack tied `emitFile` ? [plugin.js#L118](https://github.com/JetBrains/svg-mixer/blob/master/packages/postcss-svg-mixer/lib/plugin.js#L118]

**Comment by kisenka** [comment]
@thollander this is intended behaviour, postcss-svg-mixer leaves further sprite file processing to user as it shown in [example](https://github.com/JetBrains/svg-mixer/tree/master/packages/postcss-svg-mixer#usage):

```js
const { writeFileSync } = require('fs');
const postcss = require('postcss');
const mixer = require('postcss-svg-mixer');

postcss()
  .use(mixer())
  .process('.img {background: url(img.svg)}')
  .then(result => {
    const msg = result.messages.find(m => m.kind === 'sprite');
    writeFileSync(msg.filename, msg.content);
  });
```

In webpack environment postcss-svg-mixer emits a file, because webpack provide ability to do it. However I can add additional option to provide sprite filename and teach plugin to output it to filesystem.
